[package]
name = "mesquite"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_core = "0.6.0"
tiny-keccak = { version = "2.0", features = ["shake"] }

[dev-dependencies]
average = "0.13.1"
